#region license
// Copyright (C) 2013 Mikael Lyngvig (mikael@lyngvig.org).  All rights reserved.
//
// Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following
// conditions are met:
//
//     * Redistributions of source code must retain the above copyright notice, this list of conditions and the disclaimer below.
//     * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following
//       disclaimer in the documentation and/or other materials provided with the distribution.
//     * Neither the name of Mikael Lyngvig nor the names of its contributors may be used to endorse or promote products derived
//       from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
// BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
// SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#endregion

/** \file
 *  Defines the C source code writer.
 */

using Bacchi.Syntax;

namespace Bacchi.Writer
{
    /** Writer used to write C source code to a file. */
    public class C: Visitor
    {
        private System.IO.StreamWriter _writer;

        public C(string filename)
        {
            _writer = System.IO.File.CreateText(filename);
        }

        public void Close()
        {
            _writer.Close();
            _writer = null;
        }

        public void Sweep(Node[] nodes)
        {
            foreach (Node node in nodes)
                node.Visit(this);
        }

        public object Visit(Argument that)
        {
            that.Value.Visit(this);

            return null;
        }

        public object Visit(ArrayExpression that)
        {
            that.Array.Visit(this);
            that.Index.Visit(this);

            return null;
        }

        public object Visit(ArrayReference that)
        {
            return null;
        }

        public object Visit(ArrayType that)
        {
            return null;
        }

        public object Visit(Assignment that)
        {
            return null;
        }

        public object Visit(BinaryExpression that)
        {
            return null;
        }

        public object Visit(Block that)
        {
            Sweep(that.Definitions);
            Sweep(that.Statements);

            return null;
        }

        public object Visit(BooleanLiteral that)
        {
            return null;
        }

        public object Visit(BooleanType that)
        {
            return null;
        }

        public object Visit(CallStatement that)
        {
            return null;
        }

        public object Visit(Definition that)
        {
            return null;
        }

        public object Visit(File that)
        {
            _writer.WriteLine("/* FILE: {0} */", that.Name);
            Sweep(that.Modules);

            return null;
        }

        public object Visit(ForallStatement that)
        {
            return null;
        }

        public object Visit(Guard that)
        {
            return null;
        }

        public object Visit(IdentifierExpression that)
        {
            return null;
        }

        public object Visit(IdentifierReference that)
        {
            return null;
        }

        public object Visit(IdentifierType that)
        {
            return null;
        }

        public object Visit(IntegerExpression that)
        {
            return null;
        }

        public object Visit(IntegerLiteral that)
        {
            return null;
        }

        public object Visit(IntegerType that)
        {
            return null;
        }

        public object Visit(MemberExpression that)
        {
            return null;
        }

        public object Visit(Module that)
        {
            _writer.WriteLine("/* MODULE: {0} */", that.Name);

            Sweep(that.Definitions);
            that.Block.Visit(this);

            return null;
        }

        public object Visit(Parameter that)
        {
            return null;
        }

        public object Visit(ParenthesisExpression that)
        {
            return null;
        }

        public object Visit(Program that)
        {
            _writer.WriteLine("/* DO NOT EDIT: This file was generated by Bacchi v0.01. */");
            _writer.WriteLine();

            foreach (File file in that.Files)
                file.Visit(this);

            return null;
        }

        public object Visit(RangeType that)
        {
            return null;
        }

        public object Visit(Statement that)
        {
            return null;
        }

        public object Visit(StringLiteral that)
        {
            return null;
        }

        public object Visit(TupleExpression that)
        {
            return null;
        }

        public object Visit(TupleIndexExpression that)
        {
            return null;
        }

        public object Visit(TupleType that)
        {
            return null;
        }

        public object Visit(UnaryExpression that)
        {
            return null;
        }
    }
}

